name: Node.js CI

on:
  push:
    branches: main
  pull_request:

jobs:
  install:
    name: Checkout and Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm cache
        uses: ./.github/actions/setup-pnpm-cache

      - name: Install dependencies
        run: pnpm install

  lint_website:
    name: Run linter in website
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm cache
        uses: ./.github/actions/setup-pnpm-cache

      - name: Run lint check
        run: pnpm lint
        working-directory: website

  format_website:
    name: Run formatter in website
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm cache
        uses: ./.github/actions/setup-pnpm-cache

      - name: Run format check
        run: pnpm format.check
        working-directory: website

  lint_library:
    name: Run linter in library
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm cache
        uses: ./.github/actions/setup-pnpm-cache

      - name: Run lint check
        run: pnpm lint
        working-directory: library

      - run: pnpm lint
        working-directory: library

  test_library:
    name: Run Vitest in library
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm cache
        uses: ./.github/actions/setup-pnpm-cache

      - name: Run Vitest
        run: pnpm test
        working-directory: library
